name: villabistromobile
description: "Projeto VillaBistro recriado."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2

  pdf: ^3.10.8
  printing: 5.12.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

