name: villabistromobile
description: "Projeto VillaBistro recriado."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  pdf: ^3.10.8
  printing: ^5.14.2
  collection: ^1.18.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  url_launcher: ^6.3.0 # ADICIONE ESTA LINHA
  flutter_inappwebview: ^6.0.0 # ADICIONE ESTA LINHA
  fl_chart: ^0.68.0
  mask_text_input_formatter: ^2.9.0
  uuid: ^4.3.3
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoVilla.jpg"
  min_sdk_android: 21
  windows:
    generate: true

flutter_native_splash:
  color: "#1C3A2F"
  image: assets/images/splash_unificado.png
  android: true
  ios: true
  android_12:
    color: "#1C3A2F"
    image: assets/images/splash_unificado.png