-- Tabela de Mesas
create table public.mesas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  numero integer not null,
  status text default 'livre'::text, -- livre, ocupada, pagando
  company_id uuid references auth.users(id)
);

-- Tabela de Pedidos
create table public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  mesa_id bigint references public.mesas(id),
  status text default 'production'::text, -- awaiting_print, production, ready, finished
  company_id uuid references auth.users(id)
);